export { assertMatching, isMatching } from './assertions.js'
export { NonExhaustiveMatchError, PatternMismatchError } from './errors.js'
export { group } from './group.js'
export { match } from './match.js'
export { matchBy } from './match-by.js'
export {
  P,
  pAny,
  pArray,
  pBigint,
  pBoolean,
  pExact,
  pExclude,
  pFinite,
  pInstanceOf,
  pInteger,
  pNan,
  pNonEmptyArray,
  pNonEmptyRecord,
  pNull,
  pNumber,
  pOptional,
  pRecord,
  pRest,
  pSelect,
  pString,
  pSymbol,
  pTuple,
  pUndefined,
  pUnion,
  pWhen,
  pWildcard,
} from './patterns.js'
export type {
  AbstractConstructor,
  AnonymousSelectPattern,
  ArrayPattern,
  CaseEntry,
  CasesEntry,
  Discriminant,
  ExactPattern,
  ExcludePattern,
  FinitePattern,
  GroupedCaseEntry,
  GroupEntry,
  GuardPattern,
  InferPattern,
  InstanceOfPattern,
  IntegerPattern,
  MatchedValue,
  NamedSelectPattern,
  NanPattern,
  NonEmptyArrayPattern,
  NonEmptyRecordPattern,
  OptionalPattern,
  PatternKind,
  Primitive,
  PrimitivePattern,
  PropertyPath,
  RecordPattern,
  RestPattern,
  SelectPattern,
  TuplePattern,
  UnionPattern,
  WildcardPattern,
} from './types.js'
